"""Qdrant vector-store adapter."""

from collections.abc import Sequence
from typing import Any

from qdrant_client import AsyncQdrantClient, models

from insightflow.core.config import Settings


class QdrantStore:
    """Store and query vectors generated by an external embedding provider."""

    def __init__(self, settings: Settings) -> None:
        self.collection_name = settings.qdrant_collection
        self._client = AsyncQdrantClient(
            url=settings.qdrant_url,
            api_key=settings.qdrant_api_key or None,
        )

    async def is_available(self) -> bool:
        """Return whether Qdrant accepts a basic metadata request."""
        try:
            await self._client.get_collections()
        except Exception:
            return False
        return True

    async def upsert(
        self,
        point_ids: Sequence[str],
        vectors: Sequence[Sequence[float]],
        payloads: Sequence[dict[str, Any]],
    ) -> None:
        """Write caller-generated vectors and metadata to Qdrant."""
        if not (len(point_ids) == len(vectors) == len(payloads)):
            raise ValueError("Point IDs, vectors, and payloads must have equal lengths")
        points = [
            models.PointStruct(id=point_id, vector=list(vector), payload=payload)
            for point_id, vector, payload in zip(point_ids, vectors, payloads, strict=True)
        ]
        await self._client.upsert(collection_name=self.collection_name, points=points)

    async def search(self, vector: Sequence[float], limit: int = 5) -> list[models.ScoredPoint]:
        """Return the closest stored points for an externally generated query vector."""
        result = await self._client.query_points(
            collection_name=self.collection_name,
            query=list(vector),
            limit=limit,
            with_payload=True,
        )
        return result.points

    async def close(self) -> None:
        """Release client network resources."""
        await self._client.close()

